name: calculate
description: A new Flutter project.


version: 1.0.1+1
# version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.0 # حفظ البيانات
  clipboard: ^0.1.3 # نسخ النص
  flutter_slidable: ^3.0.1 # قابل للانزلاق

  
#  لي اضافه اللغه العربيه داخل التطبيق
dev_dependencies:
  flutter_test:
    sdk: flutter
    #   ده خاص بان التطبيق يكون عربي 
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line
    #  شاشة البداية
  flutter_native_splash: ^2.2.14
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android_gravity: center
  # في حاله الوضع المظلم 
  color_dark: "#202125"
  android: true
  ios: true
  # بعد كده اعمل رن للاوامر دي
  # flutter clean 
  # flutter pub get
  # flutter pub run flutter_native_splash:create

  flutter_lints: ^2.0.0

flutter:

 
  uses-material-design: true

  assets:
    - assets/images/splash.png
    - android\app\src\main\res\mipmap-xhdpi\ic_launcher.png

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
